# complex :: docker-compose

networks:
  complex_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: complex
    depends_on:
      - data
    ports:
      - 13080:80
    networks:
      - complex_localhost
    environment:
      ConnectionStrings__ComplexDb: 'Host=data;Database=complex;Username=postgres;Password=Pass@word'
      ConnectionStrings__ServiceBus: 'Endpoint=sb://revaturexyz-dev.servicebus.windows.net/;SharedAccessKeyName=SendListen;SharedAccessKey=yJey77ImCtHLx8c0YtvxWBXaA1Y6TMJAVTxgNsT3VWY='
  data:
    image: postgres:12.0
    networks:
      - complex_localhost
    environment:
      POSTGRES_PASSWORD: 'Pass@word'
version: '3.7'
