# housingxyz :: azure-devops

jobs:
  - job:
    displayName: 'angular.build'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          docker login --password $(DOCKER_PASS) --username $(DOCKER_USER)
          docker image build -f .docker/dockerfile -t housingxyz:latest .
          docker image tag housingxyz revaturexyz/housingxyz:latest
          docker image tag housingxyz revaturexyz/housingxyz:$(APP_VERSION)
          docker image push
        displayName: 'docker image'

name: $(date:yyyyMMdd)$(rev:.rr)
variables:
  APP_VERSION: '0.0.0'
  DOCKER_PASS: $(DOCKER_PASSWORD)
  DOCKER_USER: $(DOCKER_USERNAME)
