# housingxyz :: azure-devops

jobs:
  - job:
    displayName: 'angular.build'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - displayName: 'docker image'
        script: |
          docker image build -f .docker/dockerfile -t housingxyz
          docker image tag housingxyz revaturexyz/housingxyz:latest
          docker image tag housingxyz revaturexyz/housingxyz:$(APP_VERSION)

name: $(date:yyyyMMdd)$(rev:.rr)
variables:
  APP_VERSION: '0.0.0'
