# housingxyz :: azure-devops

jobs:
  - job:
    displayName: 'angular.build'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          docker image build -f .docker/dockerfile -t housingxyz:latest .
          docker image tag housingxyz revaturexyz/housingxyz:latest
          docker image tag housingxyz revaturexyz/housingxyz:$(APP_VERSION)
        displayName: 'docker image'

name: $(date:yyyyMMdd)$(rev:.rr)
variables:
  APP_VERSION: '0.0.0'
