# housingxyz :: azure-devops

jobs:
  - job:
    displayName: 'angular.build'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          sudo apt install --quiet --yes chromium-browser
          export SONAR_LOGIN=$(SONAR_LOGIN)
          cd angular
          npm clean-install
          npm run test
          npm run inspect
        displayName: 'sonarcloud'
      - script: |
          docker login --password $(DOCKER_PASSWORD) --username $(DOCKER_USERNAME)
          docker image build -f .docker/dockerfile -t housingxyz .
          docker image tag housingxyz revaturexyz/housingxyz:latest
          docker image tag housingxyz revaturexyz/housingxyz:$(APP_VERSION)
          docker image push revaturexyz/housingxyz:latest
          docker image push revaturexyz/housingxyz:$(APP_VERSION)
        displayName: 'docker'
      - script: |
          export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
          export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
          export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
          export ARM_TENANT_ID=$(ARM_TENANT_ID)
          cd .azure
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
        displayName: 'terraform'

name: $(date:yyyyMMdd)$(rev:.rr)
variables:
  APP_VERSION: '0.0.0'
