# housingxyz :: azure-devops

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage:
    displayName: 'build'
    jobs:
      - job:
        displayName: 'build::angular'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              cd angular
              npm clean-install
              npm run test
            displayName: 'npm test'
          - script: |
              cd angular
              npm run inspect -- -Dsonar.pullrequest.base=master -Dsonar.pullrequest.branch=$PULL_REQUEST_BRANCH -Dsonar.pullrequest.github.repository=revaturexyz/housingxyz -Dsonar.pullrequest.key=$PULL_REQUEST_KEY -Dsonar.pullrequest.provider=GitHub
            condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
            displayName: 'npm inspect::pull-request'
            env:
              PULL_REQUEST_BRANCH: $(Build.SourceBranchName)
              PULL_REQUEST_KEY: $(System.PullRequest.PullRequestNumber)
              SONAR_LOGIN: $(sonarcloud.login)
          - script: |
              cd angular
              npm run inspect
            condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
            displayName: 'npm inspect::branch'
            env:
              SONAR_LOGIN: $(sonarcloud.login)

  - stage:
    displayName: 'pack'
    jobs:
      - job:
        displayName: 'pack::angular'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Docker@2
            inputs:
              command: 'login'
              containerRegistry: 'revaturexyz-docker'
            displayName: 'docker login'
          - script: |
              docker image build -f .docker/dockerfile -t housingxyz .
            displayName: 'docker build'
          - script: |
              docker image tag housingxyz revaturexyz/housingxyz:pre
              docker image push revaturexyz/housingxyz:pre
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/broker'))
            displayName: 'docker push::pre'
          - script: |
              docker image tag housingxyz revaturexyz/housingxyz:dev
              docker image push revaturexyz/housingxyz:dev
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            displayName: 'docker push::dev'
          - script: |
              docker image tag housingxyz revaturexyz/housingxyz:stg
              docker image push revaturexyz/housingxyz:stg
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
            displayName: 'docker push::stg'
          - task: Docker@2
            inputs:
              command: 'logout'
              containerRegistry: 'revaturexyz-docker'
            displayName: 'docker logout'

  - stage:
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/broker'))
    displayName: 'deploy::pre'
    jobs:
      - job:
        displayName: 'deploy::pre::angular'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadSecureFile@1
            displayName: 'terraform login'
            inputs:
              secureFile: 'terraform.key'
            name: tfkey
          - task: DownloadSecureFile@1
            displayName: 'terraform variables'
            inputs:
              secureFile: 'terraform.pre.auto.tfvars'
            name: tfvars
          - script: |
              cp $(tfkey.secureFilePath) $HOME/.terraformrc
              cp $(tfvars.secureFilePath) .terraformio/
              cd .terraformio
              terraform init
              terraform plan -detailed-exitcode
              terraform apply -auto-approve
            displayName: 'terraform plan::pre'
            env:
              ARM_CLIENT_ID: $(arm.client.id)
              ARM_CLIENT_SECRET: $(arm.client.secret)
              ARM_SUBSCRIPTION_ID: $(arm.subscription.id)
              ARM_TENANT_ID: $(arm.tenant.id)
              CLOUDFLARE_EMAIL: $(cloudflare.email)
              CLOUDFLARE_TOKEN: $(cloudflare.token)

  - stage:
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'deploy::dev'
    jobs:
      - job:
        displayName: 'deploy::dev::angular'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadSecureFile@1
            displayName: 'terraform login'
            inputs:
              secureFile: 'terraform.key'
            name: tfkey
          - task: DownloadSecureFile@1
            displayName: 'terraform variables'
            inputs:
              secureFile: 'terraform.dev.auto.tfvars'
            name: tfvars
          - script: |
              cp $(tfkey.secureFilePath) $HOME/.terraformrc
              cp $(tfvars.secureFilePath) .terraformio/
              cd .terraformio
              terraform init
              terraform plan -detailed-exitcode
              terraform apply -auto-approve
            displayName: 'terraform plan::dev'
            env:
              ARM_CLIENT_ID: $(arm.client.id)
              ARM_CLIENT_SECRET: $(arm.client.secret)
              ARM_SUBSCRIPTION_ID: $(arm.subscription.id)
              ARM_TENANT_ID: $(arm.tenant.id)
              CLOUDFLARE_EMAIL: $(cloudflare.email)
              CLOUDFLARE_TOKEN: $(cloudflare.token)

  - stage:
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    displayName: 'deploy::stg'
    jobs:
      - job:
        displayName: 'deploy::stg::angular'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: DownloadSecureFile@1
            displayName: 'terraform login'
            inputs:
              secureFile: 'terraform.key'
            name: tfkey
          - task: DownloadSecureFile@1
            displayName: 'terraform variables'
            inputs:
              secureFile: 'terraform.stg.auto.tfvars'
            name: tfvars
          - script: |
              cp $(tfkey.secureFilePath) $HOME/.terraformrc
              cp $(tfvars.secureFilePath) .terraformio/
              cd .terraformio
              terraform init
              terraform plan -detailed-exitcode
              terraform apply -auto-approve
            displayName: 'terraform plan::stg'
            env:
              ARM_CLIENT_ID: $(arm.client.id)
              ARM_CLIENT_SECRET: $(arm.client.secret)
              ARM_SUBSCRIPTION_ID: $(arm.subscription.id)
              ARM_TENANT_ID: $(arm.tenant.id)
              CLOUDFLARE_EMAIL: $(cloudflare.email)
              CLOUDFLARE_TOKEN: $(cloudflare.token)

trigger:
  branches:
    include:
      - master
      - broker
  tags:
    include:
      - '*'
variables:
  - group: azure.vars
  - group: cloudflare.vars
  - group: sonarcloud.vars
