# room :: docker-compose

networks:
  room_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: room
    depends_on:
      - data
    ports:
      - 10080:80
    networks:
      - room_localhost
    environment:
      ConnectionStrings__RoomService: 'Host=salt.db.elephantsql.com;Database=exsekkwz;User Id=exsekkwz;Password=L5bXnAwiTDGJcJWlbw9kG5Ym1-byePNQ'
  data:
    image: postgres:12.0
    networks:
      - room_localhost
    environment:
      POSTGRES_PASSWORD: 'Password=L5bXnAwiTDGJcJWlbw9kG5Ym1-byePNQ'
version: '3.7'