# account :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- group: cloudflare.vars
- group: sonarcloud.vars
- { name: directory, value: account }
- { name: sonar.key, value: accountxyz }
- { name: sonar.name, value: ACCOUNT }
- { name: sonar.version, value: '0.0.0' }
- { name: namespace, value: Account }

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure
    - account

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure
    - account

stages:
- template: ../../.azure/stages/aspnet.yml
  parameters:
    directory: $(directory)
