# account :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- group: cloudflare.vars
- group: sonarcloud.vars

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - account

pr:
  branches:
    include:
    - master
  paths:
    include:
    - account

stages:
- template: ../../.azure/stages/build-aspnet.yml
  parameters:
    variables:
      directory: account
      sonar.key: accountxyz
      sonar.name: ACCOUNT
      sonar.version: '0.0.0'
      sonar.login: $(sonarcloud.login)
      namespace: Account
